// packages/cortex-dashboard/src/app/[locale]/processes/page.tsx
"use client";

import { useEffect, useState, useRef, useMemo, useCallback } from "react";
import { useTranslations } from "next-intl";
import {
	Search,
	Cpu,
	ArrowUpDown,
	ChevronRight,
	ChevronDown,
} from "lucide-react";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { SkeletonTable } from "@/components/skeleton";

interface ProcessNode {
	pid: number;
	ppid: number;
	user: string;
	cpu: number;
	mem: number;
	vsz: string;
	rss: string;
	tty: string;
	stat: string;
	command: string;
	children: ProcessNode[];
	depth: number;
}

function fuzzyMatch(query: string, text: string): boolean {
	if (!query) return true;
	const q = query.toLowerCase().replace(/\s+/g, "");
	const t = text.toLowerCase().replace(/\s+/g, "");
	let qi = 0;
	for (let ti = 0; ti < t.length && qi < q.length; ti++)
		if (t[ti] === q[qi]) qi++;
	return qi === q.length;
}

type SortKey = "pid" | "user" | "cpu" | "mem" | "command";

function sortNodes(
	nodes: ProcessNode[],
	key: SortKey,
	dir: "asc" | "desc",
): ProcessNode[] {
	const sorted = [...nodes].sort((a, b) => {
		if (key === "pid") return dir === "asc" ? a.pid - b.pid : b.pid - a.pid;
		if (key === "cpu" || key === "mem") {
			return dir === "asc" ? a[key] - b[key] : b[key] - a[key];
		}
		return dir === "asc"
			? a[key].localeCompare(b[key])
			: b[key].localeCompare(a[key]);
	});
	return sorted.map((n) => ({
		...n,
		children: sortNodes(n.children, key, dir),
	}));
}

function filterNodes(
	nodes: ProcessNode[],
	query: string,
): { nodes: ProcessNode[]; count: number } {
	if (!query) return { nodes, count: countAll(nodes) };
	let count = 0;
	const filtered = nodes
		.map((n) => {
			const childResult = filterNodes(n.children, query);
			const selfMatch =
				fuzzyMatch(query, n.command) ||
				fuzzyMatch(query, n.user) ||
				fuzzyMatch(query, String(n.pid));
			if (selfMatch || childResult.nodes.length > 0) {
				count += 1 + childResult.count;
				return { ...n, children: childResult.nodes };
			}
			return null;
		})
		.filter(Boolean) as ProcessNode[];
	return { nodes: filtered, count };
}

function countAll(nodes: ProcessNode[]): number {
	return nodes.reduce((s, n) => s + 1 + countAll(n.children), 0);
}

interface TreeRowProps {
	node: ProcessNode;
	sort: { key: SortKey; dir: "asc" | "desc" };
	expanded: Set<string>;
	onToggle: (pid: number) => void;
}

function TreeRow({ node, sort, expanded, onToggle }: TreeRowProps) {
	const isExpanded = expanded.has(String(node.pid));
	const hasChildren = node.children.length > 0;
	const cpu = node.cpu;
	const mem = node.mem;

	return (
		<>
			<tr
				className="border-b border-border hover:bg-muted/50"
				style={{ marginLeft: `${node.depth * 20}px` }}
			>
				<td className="py-2 pr-4">
					<div
						className="flex items-center gap-1"
						style={{ paddingLeft: `${node.depth * 16}px` }}
					>
						{hasChildren ? (
							<button
								onClick={() => onToggle(node.pid)}
								className="text-muted-foreground hover:text-foreground w-4 h-4 flex items-center justify-center"
							>
								{isExpanded ? (
									<ChevronDown className="w-3 h-3" />
								) : (
									<ChevronRight className="w-3 h-3" />
								)}
							</button>
						) : (
							<span className="w-4" />
						)}
						<span className="font-mono text-foreground text-xs">{node.pid}</span>
					</div>
				</td>
				<td className="py-2 pr-4 text-foreground text-xs">{node.user}</td>
				<td className="py-2 pr-4 text-right">
					<span
						className={`font-mono font-medium text-xs ${cpu > 30 ? "text-destructive" : cpu > 10 ? "text-warning" : "text-success"}`}
					>
						{cpu.toFixed(1)}%
					</span>
				</td>
				<td className="py-2 pr-4 text-right">
					<span
						className={`font-mono font-medium text-xs ${mem > 10 ? "text-destructive" : mem > 5 ? "text-warning" : "text-success"}`}
					>
						{mem.toFixed(1)}%
					</span>
				</td>
				<td className="py-2 pr-4 text-right font-mono text-muted-foreground text-xs">
					{node.vsz}
				</td>
				<td className="py-2 pr-4 text-right font-mono text-muted-foreground text-xs">
					{node.rss}
				</td>
				<td className="py-2 pr-4 text-muted-foreground text-xs">{node.tty}</td>
				<td className="py-2 pr-4 text-muted-foreground text-xs">{node.stat}</td>
				<td
					className="py-2 text-foreground text-xs truncate max-w-[300px]"
					title={node.command}
				>
					{node.command}
				</td>
			</tr>
			{isExpanded &&
				node.children.map((child) => (
					<TreeRow
						key={child.pid}
						node={child}
						sort={sort}
						expanded={expanded}
						onToggle={onToggle}
					/>
				))}
		</>
	);
}

export default function ProcessesPage() {
	const t = useTranslations("Infrastructure");
	const [processes, setProcesses] = useState<ProcessNode[]>([]);
	const [search, setSearch] = useState("");
	const [sort, setSort] = useState<{ key: SortKey; dir: "asc" | "desc" }>({
		key: "cpu",
		dir: "desc",
	});
	const [expanded, setExpanded] = useState<Set<string>>(new Set());
	const [loading, setLoading] = useState(true);
	const mountedRef = useRef(true);

	useEffect(() => {
		mountedRef.current = true;
		const fetchData = async () => {
			try {
				const res = await fetch("/api/processes", { cache: "no-store" });
				if (res.ok && mountedRef.current) {
					const data = await res.json();
					setProcesses(data.processes || []);
					setLoading(false);
					// Auto-expand root nodes on first load
					setExpanded((prev) => {
						if (prev.size > 0) return prev;
						const roots = new Set<string>();
						(data.processes || []).forEach((n: ProcessNode) =>
							roots.add(String(n.pid)),
						);
						return roots;
					});
				}
			} catch {
				// polling retries in 2s
			}
		};
		fetchData();
		const interval = setInterval(fetchData, 2000);
		return () => {
			mountedRef.current = false;
			clearInterval(interval);
		};
	}, []);

	const toggleExpand = useCallback((pid: number) => {
		setExpanded((prev) => {
			const next = new Set(prev);
			const key = String(pid);
			if (next.has(key)) next.delete(key);
			else next.add(key);
			return next;
		});
	}, []);

	const sorted = useMemo(
		() => sortNodes(processes, sort.key, sort.dir),
		[processes, sort],
	);
	const filtered = useMemo(() => filterNodes(sorted, search), [sorted, search]);

	function toggleSort(key: SortKey) {
		setSort((prev) => ({
			key,
			dir: prev.key === key && prev.dir === "asc" ? "desc" : "asc",
		}));
	}

	const thBtn = (label: string, k: SortKey, right?: boolean) => (
		<button
			onClick={() => toggleSort(k)}
			className={`flex items-center gap-1 hover:text-foreground transition-colors ${right ? "justify-end w-full" : ""}`}
		>
			{label}
			<ArrowUpDown
				className={`w-3 h-3 ${sort.key === k ? "text-primary" : "text-muted-foreground/40"}`}
			/>
		</button>
	);

	return (
		<div className="flex flex-col gap-6 p-6">
			<PageHeader
				title={t("ProcessesTitle")}
				description={t("ProcessesDescription")}
				icon={<Cpu />}
				actions={
					<div className="flex items-center gap-3">
						<span className="text-sm text-muted-foreground">
							{filtered.count} {t("ProcessesTitle").toLowerCase()}
						</span>
						<div className="relative max-w-xs">
							<Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
							<input
								type="text"
								value={search}
								onChange={(e) => setSearch(e.target.value)}
								placeholder={t("SearchProcesses")}
								className="pl-9 pr-3 py-1.5 bg-secondary border border-border rounded-lg text-xs text-foreground placeholder:text-muted-foreground focus:outline-none focus:border-ring"
							/>
						</div>
					</div>
				}
			/>
			<Card>
				<CardContent className="overflow-x-auto">
					{loading ? (
						<SkeletonTable rows={8} cols={9} />
					) : filtered.nodes.length === 0 ? (
						<EmptyState title={t("NoProcesses")} />
					) : (
						<table className="w-full text-left">
							<thead>
								<tr className="border-b border-border">
									<th className="pb-3 pr-4 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
										{thBtn("PID", "pid")}
									</th>
									<th className="pb-3 pr-4 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
										{thBtn("User", "user")}
									</th>
									<th className="pb-3 pr-4 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider text-right">
										{thBtn("CPU%", "cpu", true)}
									</th>
									<th className="pb-3 pr-4 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider text-right">
										{thBtn("Mem%", "mem", true)}
									</th>
									<th className="pb-3 pr-4 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider text-right">
										{thBtn("VSZ", "mem", true)}
									</th>
									<th className="pb-3 pr-4 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider text-right">
										{thBtn("RSS", "mem", true)}
									</th>
									<th className="pb-3 pr-4 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
										{thBtn("TTY", "user")}
									</th>
									<th className="pb-3 pr-4 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
										{thBtn("Stat", "user")}
									</th>
									<th className="pb-3 text-[11px] font-semibold text-muted-foreground uppercase tracking-wider">
										{thBtn("Command", "command")}
									</th>
								</tr>
							</thead>
							<tbody className="text-xs">
								{filtered.nodes.map((n) => (
									<TreeRow
										key={n.pid}
										node={n}
										sort={sort}
										expanded={expanded}
										onToggle={toggleExpand}
									/>
								))}
							</tbody>
						</table>
					)}
				</CardContent>
			</Card>
		</div>
	);
}

// packages/dashboard/src/routes/(authed)/processes/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import type { ProcessInfo } from '$lib/types/dashboard';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import Progress from '$lib/components/ui/progress/Progress.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import Input from '$lib/components/ui/input/Input.svelte';
	import EmptyState from '$lib/components/ui/EmptyState.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import Cpu from '$lib/icons/Cpu.svelte';
	import Menu from '$lib/icons/Menu.svelte';
	import Network from '$lib/icons/Network.svelte';
	import Search from '$lib/icons/Search.svelte';
	import { t } from '$lib/i18n';
	import TreeGroupItem from './TreeGroupItem.svelte';

	interface Props {
		data: PageData;
	}

	let { data }: Props = $props();

	let processes = $state<ProcessInfo[]>([]);
	let loading = $state(true);
	let view = $state<'list' | 'tree'>('list');
	let q = $state('');
	let sortKey = $state<'pid' | 'user' | 'cpu' | 'mem' | 'command'>('cpu');
	let sortDir = $state<'asc' | 'desc'>('desc');

	async function fetchProcesses() {
		try {
			const res = await fetch('/api/processes', { credentials: 'include' });
			if (!res.ok) throw new Error('fetch failed');
			const payload = (await res.json()) as { processes: ProcessInfo[] };
			processes = payload.processes ?? [];
		} catch {
			// keep existing on error
		} finally {
			loading = false;
		}
	}

	$effect(() => {
		void fetchProcesses();
		const id = setInterval(() => void fetchProcesses(), 3000);
		return () => clearInterval(id);
	});

	const title = $derived(t(data.messages, 'app.nav.processes'));

	const totalCpu = $derived(processes.reduce((s, p) => s + p.cpu, 0));
	const totalMem = $derived(processes.reduce((s, p) => s + p.mem, 0));

	function toggleSort(key: typeof sortKey) {
		if (sortKey === key) {
			sortDir = sortDir === 'asc' ? 'desc' : 'asc';
		} else {
			sortKey = key;
			sortDir = 'desc';
		}
	}

	const filtered = $derived.by(() => {
		const needle = q.trim().toLowerCase();
		if (!needle) return processes;
		return processes.filter(
			(p) =>
				p.command.toLowerCase().includes(needle) ||
				p.user.toLowerCase().includes(needle) ||
				String(p.pid).includes(needle),
		);
	});

	const sorted = $derived.by(() => {
		const cmp = (a: ProcessInfo, b: ProcessInfo) => {
			const av = a[sortKey];
			const bv = b[sortKey];
			if (typeof av === 'number' && typeof bv === 'number') return av - bv;
			return String(av).localeCompare(String(bv));
		};
		return [...filtered].sort((a, b) => {
			const r = cmp(a, b);
			return sortDir === 'asc' ? r : -r;
		});
	});

	const treeGroups = $derived.by(() => {
		const needle = q.trim().toLowerCase();
		const map = new Map<string, ProcessInfo[]>();
		for (const p of processes) {
			if (
				needle &&
				!(p.command.toLowerCase().includes(needle) || p.user.toLowerCase().includes(needle) || String(p.pid).includes(needle))
			)
				continue;
			const arr = map.get(p.user) ?? [];
			arr.push(p);
			map.set(p.user, arr);
		}
		return [...map.entries()]
			.map(([user, items]) => ({
				user,
				items: items.sort((a, b) => b.cpu - a.cpu),
				cpu: items.reduce((s, x) => s + x.cpu, 0),
				mem: items.reduce((s, x) => s + x.mem, 0),
			}))
			.sort((a, b) => b.cpu - a.cpu);
	});
</script>

<svelte:head>
	<title>{title} · CortexOS</title>
</svelte:head>

<div class="flex flex-col gap-5">
	<PageHeader
		{title}
		description="{processes.length} processes · CPU {totalCpu.toFixed(1)}% · MEM {totalMem.toFixed(1)}%"
		icon={Cpu}
	>
		{#snippet actions()}
			<div class="flex items-center gap-1 rounded-md border p-0.5 bg-muted/30">
				<Button
					size="sm"
					variant={view === 'list' ? 'default' : 'ghost'}
					onclick={() => (view = 'list')}
					class="h-7 px-2 text-xs gap-1.5"
				>
					<Menu class="size-3.5" /> List
				</Button>
				<Button
					size="sm"
					variant={view === 'tree' ? 'default' : 'ghost'}
					onclick={() => (view = 'tree')}
					class="h-7 px-2 text-xs gap-1.5"
				>
					<Network class="size-3.5" /> Tree
				</Button>
			</div>
		{/snippet}
	</PageHeader>

	{#if view === 'list'}
		<div class="flex flex-col gap-2">
			<div class="flex items-center gap-2">
				<div class="relative max-w-md flex-1">
					<Search class="size-4 absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground" />
					<Input
						type="search"
						value={q}
						oninput={(e) => (q = (e.currentTarget as HTMLInputElement).value)}
						placeholder="Filter by command, user or pid…"
						class="pl-8 h-9"
					/>
				</div>
				<span class="text-xs text-muted-foreground">{sorted.length} rows</span>
			</div>
			<div class="border rounded-md overflow-hidden">
				<table class="w-full caption-bottom text-sm">
					<thead class="bg-muted/40">
						<tr>
							{@render SortHead('pid', 'PID', 'w-20')}
							{@render SortHead('user', 'User')}
							{@render SortHead('command', 'Command')}
							{@render SortHead('cpu', 'CPU %', 'w-44')}
							{@render SortHead('mem', 'MEM %', 'w-44')}
						</tr>
					</thead>
					<tbody class="divide-y">
						{#if sorted.length === 0}
							<tr>
								<td colspan={5} class="text-center text-muted-foreground py-8">No results.</td>
							</tr>
						{:else}
							{#each sorted as p (p.pid)}
								<tr class="hover:bg-muted/30">
									<td class="px-3 py-2"><span class="font-mono tabular-nums">{p.pid}</span></td>
									<td class="px-3 py-2">{p.user}</td>
									<td class="px-3 py-2">
										<span class="font-mono text-xs truncate block max-w-[420px]" title={p.command}>{p.command}</span>
									</td>
									<td class="px-3 py-2">
										<div class="flex items-center gap-2 w-44">
											<Progress value={p.cpu} class="h-1.5 w-20" />
											<span class="tabular-nums text-xs">{p.cpu.toFixed(1)}</span>
										</div>
									</td>
									<td class="px-3 py-2">
										<div class="flex items-center gap-2 w-44">
											<Progress value={p.mem} class="h-1.5 w-20" />
											<span class="tabular-nums text-xs">{p.mem.toFixed(1)}</span>
										</div>
									</td>
								</tr>
							{/each}
						{/if}
					</tbody>
				</table>
			</div>
		</div>
	{:else}
		<div class="space-y-3">
			<div class="relative max-w-md">
				<Search class="size-4 absolute left-2.5 top-1/2 -translate-y-1/2 text-muted-foreground" />
				<Input
					type="search"
					value={q}
					oninput={(e) => (q = (e.currentTarget as HTMLInputElement).value)}
					placeholder="Filter by command, user or pid…"
					class="pl-8 h-9"
				/>
			</div>
			{#if treeGroups.length === 0}
				<Card>
					<EmptyState
						title="No processes match"
						description="Try clearing the filter."
						icon={Cpu}
					/>
				</Card>
			{:else}
				<div class="border rounded-md divide-y bg-card">
					{#each treeGroups as group (group.user)}
						{@render TreeGroup({group})}
					{/each}
				</div>
			{/if}
		</div>
	{/if}
</div>

{#snippet SortHead(key: typeof sortKey, label: string, className = '')}
	<th class="px-3 py-2 text-left text-xs font-medium text-muted-foreground {className}">
		<button type="button" class="inline-flex items-center gap-1 hover:text-foreground" onclick={() => toggleSort(key)}>
			{label}
			{#if sortKey === key}
				<span aria-hidden="true">{sortDir === 'asc' ? '↑' : '↓'}</span>
			{/if}
		</button>
	</th>
{/snippet}

{#snippet TreeGroup({ group }: { group: { user: string; items: ProcessInfo[]; cpu: number; mem: number } })}
	<TreeGroupItem {group} />
{/snippet}
