// src/components/ui/empty-state.tsx
"use client"

import * as React from "react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"

interface EmptyStateCTAProps {
  label: string
  onClick?: () => void
  href?: string
}

interface EmptyStateProps extends React.ComponentProps<"div"> {
  icon?: React.ReactNode
  title: string
  description?: string
  cta?: EmptyStateCTAProps
}

function EmptyState({
  icon,
  title,
  description,
  cta,
  className,
  ...props
}: EmptyStateProps) {
  return (
    <div
      data-slot="empty-state"
      className={cn(
        "flex flex-col items-center justify-center gap-3 py-12 text-center",
        className
      )}
      {...props}
    >
      {icon && (
        <div className="flex size-12 items-center justify-center rounded-full bg-muted text-muted-foreground">
          {icon}
        </div>
      )}
      <div className="flex flex-col gap-1">
        <p className="text-sm font-medium text-foreground">{title}</p>
        {description && (
          <p className="text-sm text-muted-foreground">{description}</p>
        )}
      </div>
      {cta && (
        <Button
          variant="outline"
          size="sm"
          onClick={cta.onClick}
          {...(cta.href ? { render: <a href={cta.href} /> } : {})}
        >
          {cta.label}
        </Button>
      )}
    </div>
  )
}

export { EmptyState }
export type { EmptyStateProps, EmptyStateCTAProps }

// packages/dashboard/src/lib/components/ui/empty-state/EmptyState.svelte
<!--
  EmptyState — placeholder for "no data" sections.
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils/cn';
  type Props = {
    title?: string;
    description?: string;
    icon?: Snippet;
    action?: Snippet;
    class?: string;
    children?: Snippet;
  };
  let { title, description, icon, action, class: className, children }: Props = $props();
</script>

<div
  data-slot="empty-state"
  class={cn('flex flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-border p-8 text-center', className)}
>
  {#if icon}
    <div class="text-muted-foreground [&>svg]:size-10">
      {@render icon()}
    </div>
  {/if}
  {#if title}
    <h3 data-slot="empty-state-title" class="text-sm font-semibold">{title}</h3>
  {/if}
  {#if description}
    <p data-slot="empty-state-description" class="text-sm text-muted-foreground">{description}</p>
  {/if}
  {#if action}
    <div class="mt-2">
      {@render action()}
    </div>
  {/if}
  {#if children}
    {@render children()}
  {/if}
</div>
