// packages/dashboard/src/lib/components/ui/empty-state/EmptyState.svelte
<!--
  EmptyState — placeholder for "no data" sections.
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils/cn';
  type Props = {
    title?: string;
    description?: string;
    icon?: Snippet;
    action?: Snippet;
    class?: string;
    children?: Snippet;
  };
  let { title, description, icon, action, class: className, children }: Props = $props();
</script>

<div
  data-slot="empty-state"
  class={cn('flex flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-border p-8 text-center', className)}
>
  {#if icon}
    <div class="text-muted-foreground [&>svg]:size-10">
      {@render icon()}
    </div>
  {/if}
  {#if title}
    <h3 data-slot="empty-state-title" class="text-sm font-semibold">{title}</h3>
  {/if}
  {#if description}
    <p data-slot="empty-state-description" class="text-sm text-muted-foreground">{description}</p>
  {/if}
  {#if action}
    <div class="mt-2">
      {@render action()}
    </div>
  {/if}
  {#if children}
    {@render children()}
  {/if}
</div>

// packages/dashboard-next/src/components/EmptyState.tsx
import { type ReactNode } from "react";
import { cn } from "@/lib/utils";

interface Props { icon?: ReactNode; title: string; description?: string; action?: ReactNode; className?: string }

export function EmptyState({ icon, title, description, action, className }: Props) {
  return (
    <div className={cn("flex flex-col items-center justify-center text-center py-12 px-4", className)}>
      {icon && <div className="mb-3 text-muted-foreground">{icon}</div>}
      <h3 className="text-sm font-semibold">{title}</h3>
      {description && <p className="mt-1 max-w-sm text-sm text-muted-foreground">{description}</p>}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}
