// packages/dashboard/src/lib/components/ui/EmptyState.svelte
<script lang="ts">
	import type { Component, Snippet } from 'svelte';
	import { cn } from '$lib/utils/cn';

	interface Props {
		class?: string;
		title: string;
		description?: string;
		icon?: Component;
		action?: Snippet;
	}

	let { class: className = '', title, description, icon: IconComp, action }: Props = $props();
</script>

<div
	role="status"
	class={cn(
		'flex flex-col items-center justify-center gap-3 rounded-lg border border-dashed border-border bg-card/50 p-8 text-center',
		className
	)}
>
	{#if IconComp}
		<div class="rounded-full bg-muted p-3 text-muted-foreground">
			<IconComp class="h-5 w-5" />
		</div>
	{/if}
	<div class="space-y-1">
		<h3 class="text-sm font-semibold leading-none tracking-tight">{title}</h3>
		{#if description}
			<p class="text-sm text-muted-foreground">{description}</p>
		{/if}
	</div>
	{#if action}
		<div class="pt-1">
			{@render action()}
		</div>
	{/if}
</div>

// packages/dashboard-next/src/components/EmptyState.tsx
import { type ReactNode } from "react";
import { cn } from "@/lib/utils";

interface Props { icon?: ReactNode; title: string; description?: string; action?: ReactNode; className?: string }

export function EmptyState({ icon, title, description, action, className }: Props) {
  return (
    <div className={cn("flex flex-col items-center justify-center text-center py-12 px-4", className)}>
      {icon && <div className="mb-3 text-muted-foreground">{icon}</div>}
      <h3 className="text-sm font-semibold">{title}</h3>
      {description && <p className="mt-1 max-w-sm text-sm text-muted-foreground">{description}</p>}
      {action && <div className="mt-4">{action}</div>}
    </div>
  );
}
