// packages/dashboard/src/lib/components/ui/page-header/PageHeader.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils/cn';
  type Props = {
    title: string;
    description?: string;
    icon?: Snippet;
    actions?: Snippet;
    breadcrumb?: Snippet;
    class?: string;
  };
  let { title, description, icon, actions, breadcrumb, class: className }: Props = $props();
</script>

<header data-slot="page-header" class={cn('flex flex-col gap-3', className)}>
  {#if breadcrumb}
    <div data-slot="page-header-breadcrumb">{@render breadcrumb()}</div>
  {/if}
  <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
    <div class="flex items-start gap-3">
      {#if icon}
        <div class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground [&>svg]:size-5">
          {@render icon()}
        </div>
      {/if}
      <div class="flex flex-col gap-1">
        <h1 data-slot="page-header-title" class="text-2xl font-semibold tracking-tight text-foreground">
          {title}
        </h1>
        {#if description}
          <p data-slot="page-header-description" class="text-sm text-muted-foreground">{description}</p>
        {/if}
      </div>
    </div>
    {#if actions}
      <div data-slot="page-header-actions" class="flex shrink-0 items-center gap-2 sm:justify-end">
        {@render actions()}
      </div>
    {/if}
  </div>
</header>

// packages/dashboard-next/src/components/PageHeader.tsx
import type { ReactNode } from "react";

export function PageHeader({
  icon,
  title,
  description,
  actions,
}: {
  icon?: ReactNode;
  title: string;
  description?: string;
  actions?: ReactNode;
}) {
  return (
    <header className="flex flex-col gap-3 pb-5 sm:flex-row sm:items-end sm:justify-between">
      <div className="flex items-start gap-3">
        {icon && (
          <div className="grid size-10 shrink-0 place-items-center rounded-lg bg-accent text-accent-foreground">
            {icon}
          </div>
        )}
        <div>
          <h1 className="text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            {title}
          </h1>
          {description && <p className="mt-0.5 text-sm text-muted-foreground">{description}</p>}
        </div>
      </div>
      {actions && <div className="flex flex-wrap items-center gap-2">{actions}</div>}
    </header>
  );
}
