// packages/dashboard/src/lib/components/ui/page-header/PageHeader.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { cn } from '$lib/utils/cn';
  type Props = {
    title: string;
    description?: string;
    icon?: Snippet;
    actions?: Snippet;
    breadcrumb?: Snippet;
    class?: string;
  };
  let { title, description, icon, actions, breadcrumb, class: className }: Props = $props();
</script>

<header data-slot="page-header" class={cn('flex flex-col gap-3', className)}>
  {#if breadcrumb}
    <div data-slot="page-header-breadcrumb">{@render breadcrumb()}</div>
  {/if}
  <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
    <div class="flex items-start gap-3">
      {#if icon}
        <div class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground [&>svg]:size-5">
          {@render icon()}
        </div>
      {/if}
      <div class="flex flex-col gap-1">
        <h1 data-slot="page-header-title" class="text-2xl font-semibold tracking-tight text-foreground">
          {title}
        </h1>
        {#if description}
          <p data-slot="page-header-description" class="text-sm text-muted-foreground">{description}</p>
        {/if}
      </div>
    </div>
    {#if actions}
      <div data-slot="page-header-actions" class="flex shrink-0 items-center gap-2 sm:justify-end">
        {@render actions()}
      </div>
    {/if}
  </div>
</header>

// packages/cortex-dashboard/src/components/ui/page-header.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

interface PageHeaderProps extends Omit<React.ComponentProps<"div">, "title"> {
  title: React.ReactNode
  description?: React.ReactNode
  icon?: React.ReactNode
  actions?: React.ReactNode
  breadcrumb?: React.ReactNode
}

function PageHeader({
  title,
  description,
  icon,
  actions,
  breadcrumb,
  className,
  ...props
}: PageHeaderProps) {
  return (
    <div
      data-slot="page-header"
      className={cn("flex flex-col gap-3", className)}
      {...props}
    >
      {breadcrumb && <div data-slot="page-header-breadcrumb">{breadcrumb}</div>}
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div className="flex items-start gap-3">
          {icon && (
            <div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground [&>svg]:size-5">
              {icon}
            </div>
          )}
          <div className="flex flex-col gap-1">
            <h1
              data-slot="page-header-title"
              className="font-heading text-2xl font-semibold leading-tight tracking-tight text-foreground"
            >
              {title}
            </h1>
            {description && (
              <p
                data-slot="page-header-description"
                className="text-sm text-muted-foreground"
              >
                {description}
              </p>
            )}
          </div>
        </div>
        {actions && (
          <div
            data-slot="page-header-actions"
            className="flex shrink-0 items-center gap-2 sm:justify-end"
          >
            {actions}
          </div>
        )}
      </div>
    </div>
  )
}

export { PageHeader }
export type { PageHeaderProps }
