// packages/dashboard-next/src/components/MetricCard.tsx
import { Card, CardContent } from "@/components/ui/card";
import { cn } from "@/lib/utils";
import type { ReactNode } from "react";

interface Props {
  label: string;
  value: ReactNode;
  hint?: ReactNode;
  icon?: ReactNode;
  trend?: ReactNode;
  /** "vertical" stacks trend under text. "horizontal" puts trend on the right. */
  orientation?: "vertical" | "horizontal";
  className?: string;
}

export function MetricCard({
  label,
  value,
  hint,
  icon,
  trend,
  orientation = "vertical",
  className,
}: Props) {
  const horizontal = orientation === "horizontal";
  return (
    <Card className={cn("elev-1 h-full w-full flex flex-col overflow-hidden", className)}>
      <CardContent
        className={cn(
          "p-4 flex-1 min-h-0",
          horizontal ? "flex items-stretch gap-3" : "flex flex-col gap-3",
        )}
      >
        <div
          className={cn(
            "flex items-start justify-between gap-2",
            horizontal && "flex-col flex-1 min-w-0",
          )}
        >
          <div className="space-y-1 min-w-0 flex-1">
            <p className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground truncate">
              {label}
            </p>
            <p className="text-2xl font-semibold tabular-nums leading-tight truncate">{value}</p>
            {hint && <p className="text-xs text-muted-foreground truncate">{hint}</p>}
          </div>
          {icon && !horizontal && <div className="text-muted-foreground shrink-0">{icon}</div>}
        </div>
        {trend && (
          <div
            className={cn(
              "min-h-0 overflow-hidden",
              horizontal ? "flex-1 min-w-0 self-stretch" : "mt-auto flex-1",
            )}
          >
            {trend}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

// packages/dashboard/src/lib/components/ui/metric-card/MetricCard.svelte
<script lang="ts">
	import type { Component, Snippet } from 'svelte';
	import { cn } from '$lib/utils/cn';

	interface Props {
		label: string;
		value: string | Snippet;
		hint?: string;
		icon?: Component;
		trend?: Snippet;
		orientation?: 'vertical' | 'horizontal';
		class?: string;
	}

	let {
		label,
		value,
		hint,
		icon: IconComp,
		trend,
		orientation = 'vertical',
		class: className = '',
	}: Props = $props();
</script>

<div class={cn('glass-panel h-full w-full flex flex-col overflow-hidden', className)}>
	<div
		class={cn(
			'p-4 flex-1 min-h-0',
			orientation === 'horizontal' ? 'flex items-stretch gap-3' : 'flex flex-col gap-3',
		)}
	>
		<div
			class={cn(
				'flex items-start justify-between gap-2',
				orientation === 'horizontal' && 'flex-col flex-1 min-w-0',
			)}
		>
			<div class="space-y-1 min-w-0 flex-1">
				<p class="text-[11px] font-medium uppercase tracking-wide text-muted-foreground truncate">
					{label}
				</p>
				<p class="text-2xl font-semibold tabular-nums leading-tight truncate">
					{#if typeof value === 'string'}
						{value}
					{:else}
						{@render value()}
					{/if}
				</p>
				{#if hint}
					<p class="text-xs text-muted-foreground truncate">{hint}</p>
				{/if}
			</div>
			{#if IconComp && orientation !== 'horizontal'}
				<IconComp class="h-4 w-4 text-muted-foreground shrink-0" />
			{/if}
		</div>
		{#if trend}
			<div
				class={cn(
					'min-h-0 overflow-hidden',
					orientation === 'horizontal' ? 'flex-1 min-w-0 self-stretch' : 'mt-auto flex-1',
				)}
			>
				{@render trend()}
			</div>
		{/if}
	</div>
</div>
