// packages/dashboard/src/lib/components/shell/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/state';
	import { NAV_GROUPS, type NavItem } from '$lib/nav';
	import { t, type Messages } from '$lib/i18n';
	import { cn } from '$lib/utils/cn';
	import Command from '$lib/icons/Command.svelte';

	interface Props {
		messages: Messages;
		isAdmin: boolean;
		collapsed?: boolean;
		class?: string;
	}

	let { messages, isAdmin, collapsed = false, class: className = '' }: Props = $props();

	const groups = $derived(
		NAV_GROUPS.map((g) => ({
			...g,
			items: g.items.filter((it) => (it.requiresAdmin ? isAdmin : true) && !it.hiddenInSidebar)
		}))
	);

	function isActive(href: string | null): boolean {
		if (!href) return false;
		const path = page.url.pathname;
		return path === href || path.startsWith(href + '/');
	}

	function labelOf(item: NavItem): string {
		return item.label.includes('.') ? t(messages, item.label) : item.label;
	}
</script>

<aside
	aria-label="Primary navigation"
	class={cn(
		'flex h-full flex-col border-r border-sidebar-border bg-sidebar text-sidebar-foreground',
		collapsed ? 'w-14' : 'w-60',
		'transition-[width] duration-150',
		className
	)}
>
	<div class={cn('flex items-center gap-2 border-b border-sidebar-border px-3 py-3', collapsed && 'justify-center')}>
		<span class="grid h-7 w-7 place-items-center rounded-md bg-sidebar-primary text-sidebar-primary-foreground">
			<Command class="h-4 w-4" />
		</span>
		{#if !collapsed}
			<div class="flex flex-col leading-tight">
				<span class="text-sm font-semibold">{t(messages, 'app.shell.title')}</span>
				<span class="text-[10px] uppercase tracking-wider text-muted-foreground">M1 foundation</span>
			</div>
		{/if}
	</div>

	<nav class="flex-1 overflow-y-auto px-2 py-3 scrollbar-thin">
		{#each groups as group (group.id)}
			{#if group.items.length}
				<div class="mb-3">
					{#if !collapsed}
						<h2 class="px-2 pb-1 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
							{t(messages, group.label)}
						</h2>
					{/if}
					<ul class="flex flex-col gap-0.5">
						{#each group.items as item (item.id)}
							{@const Icon = item.icon}
							{@const active = isActive(item.href)}
							<li>
								{#if item.href}
									<a
										href={item.href}
										aria-current={active ? 'page' : undefined}
										class={cn(
											'flex items-center gap-2 rounded-md px-2 py-1.5 text-sm transition-colors',
											active
												? 'bg-sidebar-accent text-sidebar-accent-foreground font-medium'
												: 'hover:bg-sidebar-accent/60 hover:text-sidebar-accent-foreground',
											collapsed && 'justify-center'
										)}
										title={collapsed ? labelOf(item) : undefined}
									>
										{#if Icon}
											<Icon class="h-4 w-4 shrink-0" />
										{/if}
										{#if !collapsed}
											<span class="truncate">{labelOf(item)}</span>
											{#if item.workstream}
												<span
													class="ml-auto rounded-full border border-sidebar-border bg-sidebar px-1.5 py-0.5 text-[9px] uppercase tracking-wide text-muted-foreground"
												>
													{item.workstream}
												</span>
											{/if}
										{/if}
									</a>
								{:else if !collapsed}
									<span
										class="flex items-center gap-2 rounded-md px-2 py-1.5 text-sm text-muted-foreground"
										title="Coming in {item.workstream ?? 'a later milestone'}"
									>
										{#if Icon}
											<Icon class="h-4 w-4 shrink-0" />
										{/if}
										<span class="truncate">{labelOf(item)}</span>
										{#if item.workstream}
											<span
												class="ml-auto rounded-full border border-sidebar-border bg-sidebar px-1.5 py-0.5 text-[9px] uppercase tracking-wide text-muted-foreground"
											>
												{item.workstream}
											</span>
										{/if}
									</span>
								{/if}
							</li>
						{/each}
					</ul>
				</div>
			{/if}
		{/each}
	</nav>

	<footer
		class={cn('border-t border-sidebar-border px-3 py-2 text-[10px] text-muted-foreground', collapsed && 'text-center')}
	>
		{#if collapsed}
			v0.2
		{:else}
			CortexOS · v0.2.0
		{/if}
	</footer>
</aside>

// packages/dashboard/src/app/sys-pilot/Sidebar.tsx
"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { Activity, ChevronDown, X } from "lucide-react";
import { useState } from "react";
import { NAV_GROUPS } from "@/components/layout/nav-config";
import { useAuth } from "@/hooks/useAuth";
import { cn } from "@/lib/utils";

interface Props { collapsed: boolean; mobileOpen: boolean; onClose: () => void }

export function Sidebar({ collapsed, mobileOpen, onClose }: Props) {
  const { user } = useAuth();
  const path = usePathname() ?? "/";
  const [adminOpen, setAdminOpen] = useState(true);

  return (
    <>
      {mobileOpen && (
        <div className="fixed inset-0 z-40 bg-black/50 md:hidden" onClick={onClose} aria-hidden />
      )}
      <aside
        className={cn(
          "z-50 bg-sidebar text-sidebar-foreground border-r border-sidebar-border shrink-0 flex flex-col",
          "fixed inset-y-0 left-0 transform transition-transform md:relative md:translate-x-0",
          mobileOpen ? "translate-x-0" : "-translate-x-full",
          collapsed ? "md:w-16" : "md:w-60",
          "w-64",
        )}
      >
        <div className="h-14 flex items-center justify-between border-b border-sidebar-border px-3">
          <Link href="/overview" className="flex items-center gap-2 min-w-0">
            <div className="grid size-7 place-items-center rounded-md bg-primary text-primary-foreground shrink-0">
              <Activity className="size-4" />
            </div>
            {!collapsed && <span className="font-semibold tracking-tight truncate">CortexOS</span>}
          </Link>
          <button type="button" onClick={onClose} className="md:hidden text-sidebar-foreground/60" aria-label="Close">
            <X className="size-4" />
          </button>
        </div>

        <nav className="flex-1 overflow-y-auto py-3 px-2 space-y-4">
          {NAV_GROUPS.map((group) => {
            const isAdmin = group.label === "Admin";
            if (isAdmin && !user?.is_admin) return null;
            return (
              <div key={group.label}>
                {isAdmin ? (
                  <button
                    type="button"
                    onClick={() => setAdminOpen(!adminOpen)}
                    className={cn(
                      "w-full flex items-center justify-between px-2 mb-1 text-[10px] uppercase tracking-wider text-sidebar-foreground/50 hover:text-sidebar-foreground/80",
                      collapsed && "md:hidden",
                    )}
                  >
                    <span>{group.label}</span>
                    <ChevronDown className={cn("size-3 transition-transform", !adminOpen && "-rotate-90")} />
                  </button>
                ) : (
                  <p className={cn("px-2 mb-1 text-[10px] uppercase tracking-wider text-sidebar-foreground/50", collapsed && "md:hidden")}>
                    {group.label}
                  </p>
                )}
                {(adminOpen || !isAdmin || collapsed) && (
                  <ul className="space-y-0.5">
                    {group.items.map((it) => (
                      <NavLink
                        key={it.href}
                        href={it.href}
                        icon={<it.icon className="size-4" />}
                        label={it.label}
                        active={path === it.href || path.startsWith(`${it.href}/`)}
                        collapsed={collapsed}
                        onClick={onClose}
                      />
                    ))}
                  </ul>
                )}
              </div>
            );
          })}
        </nav>

        <div className={cn("border-t border-sidebar-border p-3 space-y-2", collapsed && "md:px-2")}>
          <div className={cn("flex items-center gap-2 text-xs", collapsed && "md:justify-center")}>
            <span className="size-2 rounded-full bg-[var(--success)] animate-pulse" />
            {!collapsed && <span className="text-sidebar-foreground/70">Live</span>}
          </div>
          {!collapsed && user && (
            <div className="flex items-center gap-2 rounded-md bg-sidebar-accent/40 px-2 py-1.5">
              <div className="size-7 grid place-items-center rounded-full bg-primary text-primary-foreground text-xs font-semibold">
                {user.username.slice(0, 2).toUpperCase()}
              </div>
              <div className="min-w-0">
                <p className="text-xs font-medium truncate">{user.username}</p>
                <p className="text-[10px] text-sidebar-foreground/60">{user.is_admin ? "Admin" : "Standard"}</p>
              </div>
            </div>
          )}
        </div>
      </aside>
    </>
  );
}

function NavLink({ href, icon, label, active, collapsed, onClick }: { href: string; icon: React.ReactNode; label: string; active: boolean; collapsed: boolean; onClick: () => void }) {
  return (
    <li>
      <Link
        href={href}
        onClick={onClick}
        className={cn(
          "flex items-center gap-2.5 rounded-md px-2 py-1.5 text-sm transition-colors",
          active ? "bg-sidebar-accent text-sidebar-accent-foreground" : "text-sidebar-foreground/80 hover:bg-sidebar-accent/50 hover:text-sidebar-foreground",
          collapsed && "md:justify-center md:px-2",
        )}
        title={collapsed ? label : undefined}
      >
        <span className="shrink-0">{icon}</span>
        <span className={cn("truncate", collapsed && "md:hidden")}>{label}</span>
      </Link>
    </li>
  );
}
