// packages/cortex-dashboard/src/components/ui/button.tsx
import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center rounded-lg border border-transparent bg-clip-padding text-sm font-medium whitespace-nowrap transition-all outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground [a]:hover:bg-primary/80",
        outline:
          "border-primary/30 bg-primary/10 text-primary hover:border-primary/40 hover:bg-primary/15 aria-expanded:bg-primary/15 aria-expanded:text-primary dark:border-primary/35 dark:bg-primary/15 dark:hover:bg-primary/25",
        secondary:
          "bg-sky-500/15 text-sky-700 hover:bg-sky-500/25 aria-expanded:bg-sky-500/25 aria-expanded:text-sky-800 dark:text-sky-300",
        ghost:
          "bg-indigo-500/10 text-indigo-700 hover:bg-indigo-500/20 aria-expanded:bg-indigo-500/20 aria-expanded:text-indigo-800 dark:text-indigo-300 dark:hover:bg-indigo-500/25",
        destructive:
          "bg-destructive/15 text-destructive hover:bg-destructive/25 focus-visible:border-destructive/40 focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:hover:bg-destructive/30 dark:focus-visible:ring-destructive/40",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default:
          "h-8 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        xs: "h-6 gap-1 rounded-[min(var(--radius-md),10px)] px-2 text-xs in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-7 gap-1 rounded-[min(var(--radius-md),12px)] px-2.5 text-[0.8rem] in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3.5",
        lg: "h-9 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        icon: "size-8",
        "icon-xs":
          "size-6 rounded-[min(var(--radius-md),10px)] in-data-[slot=button-group]:rounded-lg [&_svg:not([class*='size-'])]:size-3",
        "icon-sm":
          "size-7 rounded-[min(var(--radius-md),12px)] in-data-[slot=button-group]:rounded-lg",
        "icon-lg": "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  ...props
}: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>) {
  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }

// packages/dashboard/src/lib/components/ui/button/Button.svelte
<!--
  Button — the canonical action primitive.
  Ported from packages/dashboard/src/components/ui/button.tsx (Next.js shadcn).
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { tv } from '$lib/utils/tv';
  import { cn } from '$lib/utils/cn';
  import type { Variant, Size } from './Button.types';

  type Props = {
    variant?: Variant;
    size?: Size;
    type?: 'button' | 'submit' | 'reset';
    href?: string;
    disabled?: boolean;
    loading?: boolean;
    name?: string;
    value?: string;
    form?: string;
    id?: string;
    class?: string;
    children?: Snippet;
    trailing?: Snippet;
    leading?: Snippet;
    onclick?: (e: MouseEvent) => void;
    'aria-label'?: string;
    'aria-labelledby'?: string;
  };

  let {
    variant = 'default',
    size = 'default',
    type = 'button',
    href,
    disabled = false,
    loading = false,
    name,
    value,
    form,
    id,
    class: className,
    children,
    trailing,
    leading,
    onclick,
    ...aria
  }: Props = $props();

  const button = tv({
    base: 'group/button inline-flex shrink-0 items-center justify-center gap-1.5 rounded-lg border border-transparent bg-clip-padding text-sm font-medium whitespace-nowrap transition-all outline-none select-none focus-visible:ring-3 focus-visible:ring-ring/50 disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20',
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:bg-primary/90',
        outline: 'border-border bg-background hover:bg-muted hover:text-foreground dark:border-input dark:bg-input/30',
        secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
        ghost: 'hover:bg-muted hover:text-foreground dark:hover:bg-muted/50',
        destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
        link: 'text-primary underline-offset-4 hover:underline',
      },
      size: {
        default: 'h-8 px-2.5',
        sm: 'h-7 rounded-md px-2.5 text-[0.8rem]',
        lg: 'h-10 px-3',
        icon: 'size-8',
      },
    },
    defaults: { variant: 'default', size: 'default' },
  });

  const classes = $derived(button({ variant, size, class: className as string | undefined }));
  const isDisabled = $derived(disabled || loading);
</script>

{#if href && !isDisabled}
  <a
    {href}
    data-slot="button"
    class={cn(classes)}
    role="button"
    aria-disabled={isDisabled}
    onclick={onclick}
    {...aria}
  >
    {#if leading}{@render leading()}{/if}
    {#if children}{@render children()}{/if}
    {#if trailing}{@render trailing()}{/if}
  </a>
{:else}
  <button
    {type}
    {name}
    {value}
    {form}
    {id}
    data-slot="button"
    class={cn(classes)}
    disabled={isDisabled}
    aria-busy={loading || undefined}
    onclick={onclick}
    {...aria}
  >
    {#if leading}{@render leading()}{/if}
    {#if children}{@render children()}{/if}
    {#if trailing}{@render trailing()}{/if}
  </button>
{/if}
