// packages/dashboard/src/lib/components/ui/incident-timeline/IncidentTimeline.svelte
<!--
  IncidentTimeline — vertical timeline of alert-history events.

  Consumes the joined alert_history + alert_rules + services shape returned
  by the healthcheck server load. Coloured dots reflect event status.
-->
<script lang="ts" module>
	export type AlertHistoryItem = {
		id: number | string;
		ruleName: string;
		serviceName: string;
		status: string;
		message: string;
		timestamp: string;
	};
</script>

<script lang="ts">
	import { cn } from '$lib/utils/cn';

	type Props = {
		alerts: AlertHistoryItem[];
		class?: string;
	};

	let { alerts, class: className = '' }: Props = $props();

	function dotColor(status: string): string {
		switch (status) {
			case 'fired':
				return 'bg-destructive';
			case 'resolved':
				return 'bg-success';
			default:
				return 'bg-primary';
		}
	}

	function relativeTime(iso: string): string {
		const t = new Date(iso).getTime();
		const diff = (Date.now() - t) / 1000;
		if (!isFinite(diff) || diff < 0) return iso;
		if (diff < 5) return 'just now';
		if (diff < 60) return `${Math.floor(diff)}s ago`;
		if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
		if (diff < 86400) return `${Math.floor(diff / 3600)}h ago`;
		return `${Math.floor(diff / 86400)}d ago`;
	}
</script>

{#if alerts.length === 0}
	<p class="text-sm text-muted-foreground">No recent incidents.</p>
{:else}
	<ol class={cn('relative ml-2 border-l pl-4 space-y-3', className)}>
		{#each alerts.slice(0, 12) as a (a.id)}
			<li class="relative">
				<span
					class={cn(
						'absolute -left-1.5 top-1.5 size-3 rounded-full ring-4 ring-background',
						dotColor(a.status)
					)}
					aria-hidden="true"
				></span>
				<div class="flex flex-wrap items-baseline gap-2 text-sm">
					<span class="font-medium">{a.ruleName}</span>
					<span class="text-xs text-muted-foreground">{a.serviceName}</span>
					<span class="ml-auto text-xs text-muted-foreground">{relativeTime(a.timestamp)}</span>
				</div>
				<p class="text-xs text-muted-foreground">{a.message}</p>
			</li>
		{/each}
	</ol>
{/if}

// packages/cortex-dashboard/src/components/sys-pilot/IncidentTimeline.tsx
import { AlertTriangle, CheckCircle2, Circle } from "lucide-react";
import type { AlertHistory } from "@/lib/types";
import { relativeTime } from "@/lib/sys-pilot/format";
import { cn } from "@/lib/utils";

export function IncidentTimeline({ items }: { items: AlertHistory[] }) {
  const sorted = [...items].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
  if (sorted.length === 0) {
    return <p className="text-sm text-muted-foreground">No incidents recorded.</p>;
  }
  return (
    <ol className="relative border-l ml-3 space-y-5 py-1">
      {sorted.map((it) => {
        const fired = it.status === "fired";
        const resolved = it.status === "resolved";
        return (
          <li key={it.id} className="ml-5 relative">
            <span
              className={cn(
                "absolute -left-[34px] top-0.5 flex size-6 items-center justify-center rounded-full ring-4 ring-background",
                fired && "bg-destructive/15 text-destructive",
                resolved && "bg-[var(--success)]/15 text-[var(--success)]",
                !fired && !resolved && "bg-muted text-muted-foreground",
              )}
            >
              {fired ? <AlertTriangle className="size-3.5" /> : resolved ? <CheckCircle2 className="size-3.5" /> : <Circle className="size-3.5" />}
            </span>
            <div className="flex items-baseline justify-between gap-3 flex-wrap">
              <h4 className="font-medium text-sm">{it.ruleName}</h4>
              <time className="text-xs text-muted-foreground tabular-nums">{relativeTime(it.timestamp)}</time>
            </div>
            <p className="text-xs text-muted-foreground mt-1">
              <span className="font-mono">{it.serviceName}</span> · {it.message}
            </p>
          </li>
        );
      })}
    </ol>
  );
}
