// packages/dashboard/src/routes/(authed)/admin/env-browser/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { t } from '$lib/i18n';
	import PageHeader from '$lib/components/ui/PageHeader.svelte';
	import EmptyState from '$lib/components/ui/EmptyState.svelte';
	import Card from '$lib/components/ui/Card.svelte';
	import Button from '$lib/components/ui/button/Button.svelte';
	import Input from '$lib/components/ui/input/Input.svelte';
	import FolderArchive from '$lib/icons/FolderArchive.svelte';
	import FileCode from '$lib/icons/FileCode.svelte';
	import Eye from '$lib/icons/Eye.svelte';
	import EyeOff from '$lib/icons/EyeOff.svelte';
	import Copy from '$lib/icons/Copy.svelte';

	interface Props {
		data: PageData;
	}

	let { data }: Props = $props();

	let selectedPath = $state<string | null>(null);
	let entries = $state<Array<{ key: string; value: string; masked: string }>>([]);
	let loading = $state(false);
	let error = $state('');
	let reveal = $state<Record<string, boolean>>({});
	let copiedKey = $state<string | null>(null);

	// Secret-reveal window state. Cleartext values only arrive from the
	// server while `secretsUnlocked` is true (a PAM-verified 10-min grant).
	let secretsUnlocked = $state(false);
	let revealExpiresAt = $state<number | null>(null);
	let showUnlock = $state(false);
	let unlockPassword = $state('');
	let unlocking = $state(false);
	let unlockError = $state('');

	async function loadFile(path: string) {
		selectedPath = path;
		loading = true;
		error = '';
		try {
			const res = await fetch(`/api/env-browser?path=${encodeURIComponent(path)}`, { credentials: 'include' });
			if (!res.ok) throw new Error(await res.text());
			const json = await res.json();
			entries = json.entries ?? [];
			secretsUnlocked = json.revealed === true;
			revealExpiresAt = json.revealExpiresAt ?? null;
			reveal = {};
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load';
			entries = [];
		} finally {
			loading = false;
		}
	}

	async function unlockSecrets(e: SubmitEvent) {
		e.preventDefault();
		if (!unlockPassword) return;
		unlocking = true;
		unlockError = '';
		try {
			const res = await fetch('/api/env-browser/unlock', {
				method: 'POST',
				credentials: 'include',
				headers: {
					'Content-Type': 'application/json',
					'X-CSRF-Token': data.session?.csrfToken ?? '',
				},
				body: JSON.stringify({ password: unlockPassword }),
			});
			if (!res.ok) {
				const body = await res.json().catch(() => null);
				throw new Error(body?.error?.message ?? 'Password verification failed');
			}
			const json = await res.json();
			revealExpiresAt = json.expiresAt ?? null;
			secretsUnlocked = true;
			showUnlock = false;
			unlockPassword = '';
			// Re-fetch the current file so cleartext values arrive.
			if (selectedPath) await loadFile(selectedPath);
		} catch (err) {
			unlockError = err instanceof Error ? err.message : 'Unlock failed';
		} finally {
			unlocking = false;
		}
	}

	function toggleReveal(key: string) {
		reveal = { ...reveal, [key]: !reveal[key] };
	}

	async function copyValue(key: string, value: string) {
		try {
			await navigator.clipboard.writeText(value);
			copiedKey = key;
			setTimeout(() => {
				if (copiedKey === key) copiedKey = null;
			}, 1200);
		} catch {
			// ignore
		}
	}

	const selectedFile = $derived(data.files.find((f) => f.path === selectedPath) ?? null);
	const groupedEntries = $derived.by(() => {
		const map = new Map<string, typeof entries>();
		for (const entry of entries) {
			const group = entry.key.split('_')[0] ?? 'General';
			const list = map.get(group) ?? [];
			list.push(entry);
			map.set(group, list);
		}
		return Array.from(map.entries()).sort((a, b) => a[0].localeCompare(b[0]));
	});
</script>

<svelte:head>
	<title>{t(data.messages, 'envBrowser.title')} · Admin · CortexOS</title>
</svelte:head>

<div class="flex flex-col gap-6">
	<PageHeader
		title={t(data.messages, 'envBrowser.title')}
		description={t(data.messages, 'envBrowser.description')}
		icon={FolderArchive}
	/>

	{#if data.files.length === 0}
		<EmptyState
			title={t(data.messages, 'envBrowser.emptyTitle')}
			description={t(data.messages, 'envBrowser.emptyDescription')}
			icon={FolderArchive}
		/>
	{:else}
		<div class="grid grid-cols-1 gap-4 lg:grid-cols-[260px_1fr]">
			<Card class="h-fit p-2">
				{#snippet children()}
					<div class="px-2 pb-2 text-[10px] uppercase tracking-wide text-muted-foreground">
						{t(data.messages, 'envBrowser.filesHeading')}
					</div>
					<div class="flex flex-col gap-1">
						{#each data.files as file}
							<button
								type="button"
								onclick={() => loadFile(file.path)}
								class={[
									'w-full rounded-md px-2 py-1.5 text-left text-sm transition-colors flex items-center gap-2',
									selectedPath === file.path
										? 'bg-accent text-accent-foreground'
										: 'hover:bg-muted/50',
								]}
							>
								<FileCode class="size-3.5 shrink-0" />
								<span class="truncate font-mono text-xs">{file.name}</span>
							</button>
						{/each}
					</div>
				{/snippet}
			</Card>

			<Card>
				{#snippet children()}
					{#if loading}
						<div class="text-sm text-muted-foreground">{t(data.messages, 'envBrowser.loading')}</div>
					{:else if error}
						<div class="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-800 dark:bg-red-900/20 dark:text-red-300">
							{error}
						</div>
					{:else if selectedFile}
						<div class="mb-3 flex items-center justify-between">
							<code class="text-xs text-muted-foreground">{selectedFile.path}</code>
							<span class="text-xs text-muted-foreground">
								{t(data.messages, 'envBrowser.keyCount').replace('{count}', String(entries.length))}
							</span>
						</div>

						<!-- Secret-reveal gate: cleartext requires a PAM-verified 10-min window. -->
						<div class="mb-3 rounded-md border border-border bg-muted/30 p-2">
							{#if secretsUnlocked}
								<div class="flex items-center gap-2 text-xs text-success">
									<Eye class="size-3.5" />
									<span>Secrets unlocked — values are shown in cleartext.</span>
								</div>
							{:else if showUnlock}
								<form class="flex items-center gap-2" onsubmit={unlockSecrets}>
									<EyeOff class="size-3.5 shrink-0 text-muted-foreground" />
									<Input
										type="password"
										bind:value={unlockPassword}
										placeholder="Your login (PAM) password"
										class="h-8 flex-1 text-xs"
									/>
									<Button type="submit" size="sm" class="h-8" disabled={unlocking || !unlockPassword}>
										{unlocking ? 'Verifying…' : 'Unlock 10 min'}
									</Button>
									<Button
										type="button"
										size="sm"
										variant="ghost"
										class="h-8"
										onclick={() => {
											showUnlock = false;
											unlockPassword = '';
											unlockError = '';
										}}
									>
										Cancel
									</Button>
								</form>
								{#if unlockError}
									<div class="mt-1 text-xs text-red-600 dark:text-red-400">{unlockError}</div>
								{/if}
							{:else}
								<div class="flex items-center justify-between gap-2">
									<div class="flex items-center gap-2 text-xs text-muted-foreground">
										<EyeOff class="size-3.5" />
										<span>Secrets are masked. Re-enter your password to reveal them.</span>
									</div>
									<Button type="button" size="sm" variant="outline" class="h-8" onclick={() => (showUnlock = true)}>
										Unlock secrets
									</Button>
								</div>
							{/if}
						</div>

						{#if entries.length === 0}
							<div class="text-sm text-muted-foreground">{t(data.messages, 'envBrowser.noEntries')}</div>
						{:else}
							<div class="space-y-4">
								{#each groupedEntries as [group, groupEntries]}
									<div>
										<h4 class="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
											{group}
										</h4>
										<div class="space-y-2">
											{#each groupEntries as entry (entry.key)}
												<div class="grid grid-cols-[180px_1fr_auto] items-center gap-2">
													<code class="truncate text-xs font-semibold">{entry.key}</code>
													<Input
														value={reveal[entry.key] ? entry.value : entry.masked}
														readonly
														type={reveal[entry.key] ? 'text' : 'password'}
														class="h-8 font-mono text-xs"
													/>
													<div class="flex gap-1">
														<Button
															size="icon"
															variant="ghost"
															class="size-8"
															onclick={() => toggleReveal(entry.key)}
															aria-label={reveal[entry.key]
																? t(data.messages, 'envBrowser.hide')
																: t(data.messages, 'envBrowser.reveal')}
														>
															{#if reveal[entry.key]}
																<EyeOff class="size-3.5" />
															{:else}
																<Eye class="size-3.5" />
															{/if}
														</Button>
														<Button
															size="icon"
															variant="ghost"
															class="size-8"
															onclick={() => copyValue(entry.key, entry.value)}
															aria-label={t(data.messages, 'envBrowser.copy')}
														>
															<Copy class={'size-3.5' + (copiedKey === entry.key ? ' text-success' : '')} />
														</Button>
													</div>
												</div>
											{/each}
										</div>
									</div>
								{/each}
							</div>
						{/if}
					{:else}
						<div class="text-sm text-muted-foreground">
							{t(data.messages, 'envBrowser.selectHint')}
						</div>
					{/if}
				{/snippet}
			</Card>
		</div>
	{/if}
</div>

// packages/dashboard/src/app/[locale]/admin/env-browser/page.tsx
"use client";

import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { FileCode, Eye, EyeOff, Copy, Search } from "lucide-react";
import { toast } from "sonner";
import { PageHeader } from "@/components/sys-pilot/PageHeader";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

// ---------------------------------------------------------------------------
// Backend shape (see src/app/api/env-browser/route.ts):
//   GET /api/env-browser?path=<abs>  ->  { path, lines: EnvLine[] }
//   where EnvLine = { line, raw, type: "kv"|"comment"|"blank",
//                     key?, value?, exported?, masked? }
// Reveal (cleartext) and POST writes require an X-Cortex-Confirmation-Token
// that has no UI-accessible mint endpoint, so those remain gated/blocked.
// ---------------------------------------------------------------------------

interface EnvLine {
  line: number;
  raw: string;
  type: "kv" | "comment" | "blank";
  key?: string;
  value?: string;
  exported?: boolean;
  masked?: string;
}

interface EnvFileResponse {
  path: string;
  lines: EnvLine[];
}

const DEFAULT_PATH = "/opt/cortexos/.secrets/9router.env";

async function fetchEnvFile(path: string): Promise<EnvFileResponse> {
  const res = await fetch(`/api/env-browser?path=${encodeURIComponent(path)}`);
  if (!res.ok) {
    const body = (await res.json().catch(() => ({}))) as { error?: string };
    throw new Error(body.error ?? `Failed to load ${path} (${res.status})`);
  }
  return (await res.json()) as EnvFileResponse;
}

export default function AdminEnvPage() {
  const [path, setPath] = useState(DEFAULT_PATH);
  const [query, setQuery] = useState(DEFAULT_PATH);
  const [reveal, setReveal] = useState<Record<string, boolean>>({});

  const { data, isLoading, error, isError } = useQuery({
    queryKey: ["env-browser", query],
    queryFn: () => fetchEnvFile(query),
    enabled: query.length > 0,
    retry: false,
  });

  // Only kv lines have keys/values to surface in the UI.
  const kvLines = useMemo(
    () => (data?.lines ?? []).filter((l): l is EnvLine & { key: string } => l.type === "kv" && !!l.key),
    [data],
  );

  // Sidebar lists the env file(s) currently loaded (no enumeration endpoint exists).
  const files = data ? [{ path: data.path, keys: kvLines.map((l) => l.key) }] : [];

  async function copyValue(key: string, displayed: string) {
    try {
      await navigator.clipboard.writeText(displayed);
      toast.success(`Copied ${key}`);
    } catch {
      toast.error(`Could not copy ${key}`);
    }
  }

  function onReveal(key: string) {
    // Cleartext reveal requires a confirmation-token handshake the dashboard UI
    // cannot mint on its own. Toggle to show whatever the backend returned
    // (masked secrets stay masked) and explain when nothing more is available.
    setReveal((s) => ({ ...s, [key]: !s[key] }));
  }

  return (
    <div className="space-y-5">
      <PageHeader title="Env Browser" description="Inspect environment secrets for managed services." />

      <Card className="p-3">
        <form
          className="flex items-center gap-2"
          onSubmit={(e) => {
            e.preventDefault();
            setQuery(path.trim());
          }}
        >
          <Search className="size-4 text-muted-foreground shrink-0" />
          <Input
            value={path}
            onChange={(e) => setPath(e.target.value)}
            placeholder="/opt/cortexos/.secrets/<file>.env"
            className="h-8 font-mono text-xs"
          />
          <Button type="submit" size="sm" disabled={!path.trim()}>
            Load
          </Button>
        </form>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-[260px_1fr] gap-4">
        <Card className="p-2 h-fit">
          <div className="text-[10px] uppercase tracking-wide text-muted-foreground px-2 pb-2">Env files</div>
          {files.length === 0 ? (
            <div className="px-2 py-1.5 text-xs text-muted-foreground">No file loaded</div>
          ) : (
            files.map((f) => (
              <div
                key={f.path}
                className="w-full text-left rounded-md px-2 py-1.5 flex items-center gap-2 text-sm bg-accent text-accent-foreground"
              >
                <FileCode className="size-3.5 shrink-0" />
                <span className="truncate font-mono text-xs">{f.path.split("/").pop()}</span>
              </div>
            ))
          )}
        </Card>

        <Card className="p-4">
          {isLoading && <div className="text-xs text-muted-foreground">Loading…</div>}
          {isError && (
            <div className="text-xs text-destructive">{error instanceof Error ? error.message : "Failed to load env file"}</div>
          )}
          {data && !isLoading && (
            <>
              <div className="flex items-center justify-between mb-3">
                <code className="text-xs text-muted-foreground">{data.path}</code>
                <span className="text-xs text-muted-foreground">{kvLines.length} keys</span>
              </div>
              <div className="space-y-2">
                {kvLines.map((l) => {
                  const k = l.key;
                  // masked present => secret key; show dots unless revealed (and a
                  // cleartext value is actually available, which it is not via masked read).
                  const isSecret = typeof l.masked === "string";
                  const cleartext = l.value ?? "";
                  const shown = reveal[k]
                    ? isSecret
                      ? "(reveal requires confirmation)"
                      : cleartext
                    : isSecret
                      ? l.masked || "••••••••"
                      : cleartext;
                  return (
                    <div key={k} className="grid grid-cols-[200px_1fr_auto] gap-2 items-center">
                      <code className="text-xs font-semibold">{k}</code>
                      <Input value={shown} readOnly className="h-8 font-mono text-xs" />
                      <div className="flex gap-1">
                        <Button size="sm" variant="ghost" onClick={() => onReveal(k)}>
                          {reveal[k] ? <EyeOff className="size-3.5" /> : <Eye className="size-3.5" />}
                        </Button>
                        <Button size="sm" variant="ghost" onClick={() => copyValue(k, shown)}>
                          <Copy className="size-3.5" />
                        </Button>
                      </div>
                    </div>
                  );
                })}
                {kvLines.length === 0 && <div className="text-xs text-muted-foreground">No keys in this file.</div>}
              </div>
            </>
          )}
        </Card>
      </div>
    </div>
  );
}
