// packages/dashboard/src/lib/components/ui/Input.svelte
<script lang="ts">
	import { cn } from '$lib/utils/cn';

	interface Props {
		class?: string;
		name?: string;
		id?: string;
		type?: 'text' | 'email' | 'password' | 'number' | 'search' | 'url' | 'tel';
		value?: string;
		placeholder?: string;
		required?: boolean;
		disabled?: boolean;
		readonly?: boolean;
		/** Browser autofill hint. Mirrors HTML `autocomplete` attribute. */
		autocomplete?: HTMLInputElement['autocomplete'];
		autofocus?: boolean;
		ariaInvalid?: boolean;
		ariaDescribedby?: string;
		minlength?: number;
		maxlength?: number;
		oninput?: (e: Event) => void;
		onchange?: (e: Event) => void;
	}

	let {
		class: className = '',
		name,
		id,
		type = 'text',
		value = $bindable(''),
		placeholder,
		required = false,
		disabled = false,
		readonly = false,
		autocomplete,
		autofocus = false,
		ariaInvalid,
		ariaDescribedby,
		minlength,
		maxlength,
		oninput,
		onchange
	}: Props = $props();
</script>

<input
	{name}
	{id}
	{type}
	bind:value
	{placeholder}
	{required}
	{disabled}
	{readonly}
	{autocomplete}
	minlength={minlength ?? null}
	maxlength={maxlength ?? null}
	aria-invalid={ariaInvalid ?? null}
	aria-describedby={ariaDescribedby ?? null}
	class={cn(
		'flex h-9 w-full rounded-md border border-input bg-background px-3 py-1 text-sm shadow-sm ' +
			'placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 ' +
			'focus-visible:ring-ring focus-visible:ring-offset-1 focus-visible:ring-offset-background ' +
			'disabled:cursor-not-allowed disabled:opacity-50',
		className
	)}
	{oninput}
	{onchange}
/>

// packages/dashboard-next/src/components/ui/input.tsx
import * as React from "react";
import { cn } from "@/lib/utils";

const Input = React.forwardRef<HTMLInputElement, React.ComponentProps<"input">>(
  ({ className, type, ...props }, ref) => {
    return (
      <input
        type={type}
        className={cn(
          "flex h-9 w-full rounded-md border border-[var(--color-border)] bg-[var(--color-background-surface)] px-3 py-1 text-base shadow-sm transition-colors",
          "file:border-0 file:bg-transparent file:text-sm file:font-medium file:text-[var(--color-text-primary)]",
          "placeholder:text-[var(--color-text-secondary)]",
          "focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[var(--color-accent)]",
          "disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
          className,
        )}
        ref={ref}
        {...props}
      />
    );
  },
);
Input.displayName = "Input";

export { Input };
