// packages/dashboard/src/lib/components/ui/separator/Separator.svelte
<script lang="ts">
  import { cn } from '$lib/utils/cn';
  type Props = {
    orientation?: 'horizontal' | 'vertical';
    class?: string;
  };
  let { orientation = 'horizontal', class: className }: Props = $props();
</script>

<div
  data-slot="separator"
  role="separator"
  aria-orientation={orientation}
  class={cn(
    'shrink-0 bg-border',
    orientation === 'horizontal' ? 'h-px w-full' : 'h-full w-px',
    className,
  )}
></div>

// packages/dashboard-next/src/components/ui/separator.tsx
import * as React from "react";
import { Divider as AstryxDivider } from "@astryxdesign/core/Divider";
import { cn } from "@/lib/utils";

const Separator = React.forwardRef<HTMLDivElement, React.ComponentProps<typeof AstryxDivider>>(
  ({ className, orientation = "horizontal", ...props }, ref) => (
    <AstryxDivider
      ref={ref}
      orientation={orientation}
      className={cn(orientation === "horizontal" ? "h-[1px] w-full" : "h-full w-[1px]", className)}
      {...props}
    />
  ),
);
Separator.displayName = "Separator";

export { Separator };
