// packages/dashboard-next/src/components/ui/button.tsx
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium cursor-pointer transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50 disabled:cursor-not-allowed [&_svg]:pointer-events-none [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground shadow hover:bg-primary/90",
        destructive: "bg-destructive text-destructive-foreground shadow-sm hover:bg-destructive/90",
        success: "bg-success text-success-foreground shadow-sm hover:bg-success/90",
        warning: "bg-warning text-warning-foreground shadow-sm hover:bg-warning/90",
        info: "bg-[var(--chart-2)] text-background shadow-sm hover:bg-[var(--chart-2)]/90",
        outline:
          "border border-input bg-background shadow-sm hover:bg-accent hover:text-accent-foreground",
        "outline-success":
          "border-0 bg-transparent text-muted-foreground hover:bg-transparent hover:text-[var(--success)] [&_svg]:text-[var(--success)] [&_svg]:transition-all [&_svg]:duration-150 [&_svg]:stroke-[1.5] hover:[&_svg]:stroke-[2.5]",
        "outline-destructive":
          "border-0 bg-transparent text-muted-foreground hover:bg-transparent hover:text-[var(--destructive)] [&_svg]:text-[var(--destructive)] [&_svg]:transition-all [&_svg]:duration-150 [&_svg]:stroke-[1.5] hover:[&_svg]:stroke-[2.5]",
        "outline-warning":
          "border-0 bg-transparent text-muted-foreground hover:bg-transparent hover:text-[var(--warning)] [&_svg]:text-[var(--warning)] [&_svg]:transition-all [&_svg]:duration-150 [&_svg]:stroke-[1.5] hover:[&_svg]:stroke-[2.5]",
        secondary: "bg-secondary text-secondary-foreground shadow-sm hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 rounded-md px-3 text-xs",
        lg: "h-10 rounded-md px-8",
        icon: "h-9 w-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>, VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button";
    return (
      <Comp className={cn(buttonVariants({ variant, size, className }))} ref={ref} {...props} />
    );
  },
);
Button.displayName = "Button";

export { Button, buttonVariants };

// packages/dashboard/src/lib/components/ui/Button.svelte
<script lang="ts" module>
	export type ButtonVariant =
		| 'default'
		| 'destructive'
		| 'outline'
		| 'secondary'
		| 'ghost'
		| 'link'
		| 'success';

	export type ButtonSize = 'sm' | 'md' | 'lg' | 'icon';

	const base =
		'inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md font-medium ' +
		'transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring ' +
		'focus-visible:ring-offset-1 focus-visible:ring-offset-background disabled:pointer-events-none ' +
		'disabled:opacity-50 select-none cursor-pointer';

	const variants: Record<ButtonVariant, string> = {
		default: 'bg-primary text-primary-foreground hover:bg-primary/90',
		destructive: 'bg-destructive text-destructive-foreground hover:bg-destructive/90',
		outline:
			'border border-input bg-background hover:bg-accent hover:text-accent-foreground',
		secondary: 'bg-secondary text-secondary-foreground hover:bg-secondary/80',
		ghost: 'hover:bg-accent hover:text-accent-foreground',
		link: 'text-primary underline-offset-4 hover:underline',
		success: 'bg-success text-success-foreground hover:bg-success/90'
	};

	const sizes: Record<ButtonSize, string> = {
		sm: 'h-8 px-3 text-sm',
		md: 'h-9 px-4 text-sm',
		lg: 'h-10 px-6 text-base',
		icon: 'h-9 w-9 p-0'
	};
</script>

<script lang="ts">
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/utils/cn';

	interface Props {
		variant?: ButtonVariant;
		size?: ButtonSize;
		type?: 'button' | 'submit' | 'reset';
		disabled?: boolean;
		loading?: boolean;
		class?: string;
		ariaLabel?: string;
		ariaControls?: string;
		ariaExpanded?: boolean;
		ariaPressed?: boolean;
		onclick?: (e: MouseEvent) => void;
		children?: Snippet;
	}

	let {
		variant = 'default',
		size = 'md',
		type = 'button',
		disabled = false,
		loading = false,
		class: className = '',
		ariaLabel,
		ariaControls,
		ariaExpanded,
		ariaPressed,
		onclick,
		children
	}: Props = $props();

	const isDisabled = $derived(Boolean(disabled || loading));
</script>

<button
	{type}
	disabled={isDisabled}
	aria-busy={loading}
	aria-label={ariaLabel}
	aria-controls={ariaControls}
	aria-expanded={ariaExpanded}
	aria-pressed={ariaPressed}
	class={cn(base, variants[variant], sizes[size], className)}
	{onclick}
>
	{#if loading}
		<span class="inline-block h-3 w-3 animate-spin rounded-full border-2 border-current border-t-transparent" aria-hidden="true"></span>
	{/if}
	{#if children}
		{@render children()}
	{/if}
</button>
