// packages/dashboard-next/src/components/ui/card.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        "rounded-xl border border-border/60 bg-card text-card-foreground elev-1",
        className,
      )}
      {...props}
    />
  ),
);
Card.displayName = "Card";

const CardHeader = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
  ),
);
CardHeader.displayName = "CardHeader";

const CardTitle = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn("font-semibold leading-none tracking-tight", className)}
      {...props}
    />
  ),
);
CardTitle.displayName = "CardTitle";

const CardDescription = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("text-sm text-muted-foreground", className)} {...props} />
  ),
);
CardDescription.displayName = "CardDescription";

const CardContent = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
  ),
);
CardContent.displayName = "CardContent";

const CardFooter = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn("flex items-center p-6 pt-0", className)} {...props} />
  ),
);
CardFooter.displayName = "CardFooter";

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent };

// packages/dashboard/src/lib/components/ui/Card.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';
	import { cn } from '$lib/utils/cn';

	interface Props {
		class?: string;
		header?: Snippet;
		title?: Snippet;
		description?: Snippet;
		footer?: Snippet;
		children?: Snippet;
	}

	let { class: className = '', header, title, description, footer, children }: Props = $props();
</script>

<section
	class={cn(
		'glass-panel flex flex-col gap-3 rounded-lg p-5 text-card-foreground',
		className
	)}
>
	{#if header || title || description}
		<header class="flex flex-col gap-1">
			{#if header}
				{@render header()}
			{:else}
				{#if title}
					<h3 class="text-base font-semibold leading-none tracking-tight">
						{@render title()}
					</h3>
				{/if}
				{#if description}
					<p class="text-sm text-muted-foreground">
						{@render description()}
					</p>
				{/if}
			{/if}
		</header>
	{/if}

	<div class="flex-1">
		{#if children}
			{@render children()}
		{/if}
	</div>

	{#if footer}
		<footer class="border-t pt-3 text-sm text-muted-foreground">
			{@render footer()}
		</footer>
	{/if}
</section>
